bwtool summary test_regions.blacklistfiltered.bed 62447_treat.bw OCI -with-sum
bwtool summary test_regions.blacklistfiltered.bed 79427_treat.bw MCF10A -with-sum
bwtool summary test_regions.blacklistfiltered.bed 79429_treat.bw MCF10A.2 -with-sum
bwtool summary test_regions.blacklistfiltered.bed 79430_treat.bw MCF10A.3 -with-sum
bwtool summary test_regions.blacklistfiltered.bed 78268_treat.bw MDAMB -with-sum
bwtool summary test_regions.blacklistfiltered.bed 44959_treat.bw HelaS3 -with-sum
bwtool summary test_regions.blacklistfiltered.bed 44960_treat.bw HelaS3.2 -with-sum
bwtool summary test_regions.blacklistfiltered.bed 41026_treat.bw EFL -with-sum
bwtool summary test_regions.blacklistfiltered.bed 40866_treat.bw EFSI -with-sum
bwtool summary test_regions.blacklistfiltered.bed 40832_treat.bw EFSI.2 -with-sum
